version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Using Node.js version:
      - node -v
      - echo Using NPM version:
      - npm -v
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
